### ISSUE TITLE
Feature Suggestion: Force Page Break

### ISSUE THREAD

**Issue by ErebusBat** [marijnbent/obsidian-print#3]
Ability to somehow force a pagebreak

**Comment by marijnbent** [comment]
Thats quite easy. Just add a CSS rule to it.

```
   page-break-before: always;
```

**Comment by marijnbent** [comment]
Thing

**Comment by marijnbent** [comment]
Did it :-)
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/cd3d3784-bd0b-42ec-822f-8c5ff2636b08">
